# -*- coding: utf-8 -*-
"""DataVisualizationExercise.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tOYrxirU7S1EN_e5CYFUwRDK9s9DyFB2
"""

from google.colab import files
uploaded = files.upload() #returns dictionary of uploaded files, keys: file names, values: file data

import pandas as pd
import io
#print(uploaded)
df = pd.read_csv(io.BytesIO(uploaded['most_subscribed_youtube_channels (4).csv']))
df = df.replace(',','')
display(df)

#notice the binary data being retrieved from file inside the ()
#io.BytesIO receives binary to create stream of data
#read_csv reads the stream since it can't read binary directly, then turned into data frame

import plotly.express as px
fig = px.histogram(df, x='subscribers', title='Subscriber Count')
fig.show()

import plotly.express as px

#df2 = pd.read_csv('most_subscribed_youtube_channels (4).csv')
#df2 = df2.replace(',','')
#display(df2)

fig = px.pie(df, values='subscribers', names='category', title='YouTube Categories')
fig.show()

import plotly.express as px

fig = px.box(df, y='started', title='Years Started',points='all')
fig.show()